// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_CLOCK1
`define ENABLE_LED
`define ENABLE_SW


module hello_world(

	//////////// CLOCK 1: 3.3-V LVTTL //////////
	input 		          		MAX10_CLK1_50,

	//////////// LED: 3.3-V LVTTL //////////
	output		     [1:0]		LEDR,


	//////////// SW: 3.3-V LVTTL //////////
	input 		     [1:0]		SW

);

// Hardware-based SW-LED connection
assign LEDR[0] = ~SW[0];

// Software-based SW-LED connection
nios_setup_v2 u0 (
	.clk_clk                           (MAX10_CLK1_50), // clk.clk
	.reset_reset_n                     (1'b1),    // reset.reset_n
	.switch_external_connection_export (SW[1]),   // switch_external_connection.export
	.led_external_connection_export    (LEDR[1])  // led_external_connection.export
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
